### ISSUE TITLE
Official Link for "ForMatter" Coprocessor Binary

### ISSUE THREAD

**Issue by chrismerck** [stm32-hotspot/stm32wb-matter-device-over-thread#2]
This repository contains a binary called `stm32wb5x_BLE_Thread_ForMatter_fw.bin`. Release notes in this repo indicate a version number of 1.0.1. Presumably this is officially signed by ST, however it's being released here in an unofficial (presumably third-party) repository. Can someone explain what is going on here? (I want to build a commercial product on top of this IC, and the binary stack is a very important but mysterious aspect of this chip.)

**Comment by STYoannZamaron** [comment]
Hello,
This binary is used only for this project and is not supported by ST for other applications. If you want to use the official version, you can download the one from the latest cube Firmware. link : https://www.st.com/en/embedded-software/stm32cubewb.html
the latest version is 1.16.0
thanks

**Comment by chrismerck** [comment]
Thank you, but which of the many official copro binaries do I need? 

I assume it's either [stm32wb5x_BLE_Thread_static_fw.bin](https://github.com/STMicroelectronics/STM32CubeWB/blob/master/Projects/STM32WB_Copro_Wireless_Binaries/STM32WB5x/stm32wb5x_BLE_Thread_static_fw.bin) or [stm32wb5x_BLE_Thread_dynamic_fw.bin](https://github.com/STMicroelectronics/STM32CubeWB/blob/master/Projects/STM32WB_Copro_Wireless_Binaries/STM32WB5x/stm32wb5x_BLE_Thread_dynamic_fw.bin), but which one?

**Comment by STYoannZamaron** [comment]
Hello,
the static use ble or thread radio, but not at the "same time".  Each time you want to change from ble or thread you need to re init the ip. In the dynamic binary you can use ble and thread at the same time.  For example, for matter we used the dynamic one because we need ble and thread at the same time for the commissioning.
